### ISSUE TITLE
Domain can not be found

### ISSUE THREAD

**Issue by mtricht** [libdns/digitalocean#1]
The following API call is made to DO: `POST https://api.digitalocean.com/v2/domains/example.com./records` returning `404 The resource you were accessing could not be found.`. There should be no dot at the end of the domain as documented here: https://developers.digitalocean.com/documentation/v2/#update-a-domain-record

**Comment by scoobybejesus** [comment]
Same issue here.

**Comment by mholt** [comment]
How can this error be reproduced?

**Comment by mtricht** [comment]
@mholt Minimal docker image with DO module:
```
FROM caddy:2-builder AS builder
RUN caddy-builder \
    github.com/caddy-dns/digitalocean

FROM caddy:2-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
Minimal caddyfile:
```
*.example.com {
  tls {
    dns digitalocean {token}
  }
}
```

**Comment by mholt** [comment]
Oh, you're using Caddy. These libraries are independent of any web server. This should probably be moved to caddy-dns/digitalocean.

**Comment by mholt** [comment]
Actually we can probably work around the problem here.
