### ISSUE TITLE
Relative/absolute record name conversions

### ISSUE THREAD

**Issue by mholt** [libdns/digitalocean#6]
Hi,

Over in the libdns repo, we're discussing standardizing the use of relative or absolute record names in `libdns.Record` structs. The current consensus is that they should be made relative (i.e. for a record named `sub.example.com` in a zone called `example.com`, the name should become `sub`). This may affect your provider implementation.

When you have a chance, would you please check out [this issue](https://github.com/libdns/libdns/issues/12#issuecomment-756135908)? This is the last call for feedback before we decide and I push the changes.

Link: https://github.com/libdns/libdns/issues/12#issuecomment-756135908

Thank you!

**Comment by GurjinderSingh** [comment]
please update this, i was going to report.

current result for me is this :crying_cat_face: 
```
_acme-challenge.sub.example.com.example.com
```

https://github.com/libdns/digitalocean/blob/186c4ebd22152458b6ad018238dd2a92311a87d0/client.go#L76
